############################################################
#### Configuration
############################################################

# Get this token here: https://developers.facebook.com/tools/explorer
# Select user_groups and read_stream as permission
facebook_token: FACEBOOK_TOKEN

# The group ID you want to export posts from. Need to be a member of this group.
facebook_group_id: FACEBOOK_GROUP_ID

# The category for the topics, will be created if needed
discourse_category_name: Category

# User with admin privileges to create users and category
discourse_admin: admin

# If true then nothing will be written to the Discourse database
test_mode: false

# User real email addresses? If not, .fake will be added to the username
real_email_addresses: false

# Import oldest (least recently changed) post first
import_oldest_first: false
